"""Frontend-only Streamlit demo for the AI Code Repair Agent."""

from html import escape

import streamlit as st


PIPELINE_STAGES = [
    "Repository Analysis",
    "Baseline Tests",
    "AI Planning",
    "Patch Generation",
    "Safety Guard",
    "Verification",
    "Test Generation",
    "Final Report",
]

DEMO_REPORT = """# AI Code Repair Agent — Demo Report

> Demonstration content only. No repair or verification has been performed.

- **Task:** Example addition function returns the wrong result.
- **Root Cause:** Example logic subtracts instead of adding.
- **Files Changed:** `calculator.py` (example only)
- **Patch:** `return a - b` → `return a + b` (example only)
- **Baseline Tests:** Not run — frontend demo
- **Final Tests:** Not run — frontend demo
- **Regression Status:** Not checked — frontend demo
- **Generated Tests:** Example only: `assert add(2, 3) == 5`
"""


def show_sidebar():
    """Collect display-only repair configuration."""
    with st.sidebar:
        st.title("Repair Configuration")
        repository_path = st.text_input(
            "Repository Path",
            placeholder="C:/Users/YourName/project",
            help="Demo input only; it is not read or analyzed.",
        )
        model = st.selectbox("Model", ["GPT", "Gemini", "Claude", "Local Model"])
        max_attempts = st.number_input(
            "Maximum Repair Attempts", min_value=1, max_value=10, value=3, step=1
        )
        test_timeout = st.number_input(
            "Test Timeout (seconds)", min_value=1, max_value=600, value=30, step=1
        )

        st.divider()
        st.subheader("Repair Pipeline")
        for index, stage in enumerate(PIPELINE_STAGES, start=1):
            st.markdown(f"**{index}.** {stage}")
        st.caption("Pipeline shown for illustration only; no stage is connected.")

    return repository_path, model, max_attempts, test_timeout


def show_header():
    st.title("AI Code Repair Agent")
    st.markdown("### Find bugs. Generate minimal fixes. Verify before accepting.")
    st.caption("Verified Autonomous Repository-Level Bug Fixing System")
    st.info(
        "**Frontend demo mode:** all plans, code, checks, and metrics below are "
        "static examples or placeholders. No backend repair logic runs."
    )


def show_request_form(repository_path, model, max_attempts, test_timeout):
    st.header("Describe the Bug")
    bug_description = st.text_area(
        "Bug description",
        placeholder="The add() function returns the wrong result when two numbers are added.",
        height=150,
        label_visibility="collapsed",
    )

    st.subheader("Target Repository")
    st.markdown(
        f'<div class="repo-path">{escape(repository_path) if repository_path else "No repository path entered"}</div>',
        unsafe_allow_html=True,
    )
    st.caption(
        f"Configuration preview · Model: {model} · Max attempts: {max_attempts} · "
        f"Test timeout: {test_timeout}s"
    )

    if st.button("🚀 Start Repair", type="primary", use_container_width=True):
        st.info("Frontend demo mode — backend integration will be connected later.")


def show_pipeline():
    st.header("Repair Pipeline")
    st.caption("Illustrative stage states only — no analysis or checks have run.")
    for start in range(0, len(PIPELINE_STAGES), 4):
        columns = st.columns(4)
        for column, stage in zip(columns, PIPELINE_STAGES[start : start + 4]):
            ready = stage == "Repository Analysis"
            dot = "🟢" if ready else "⚪"
            state = "Ready" if ready else "Waiting"
            with column:
                st.markdown(
                    f'<div class="stage-card"><div class="stage-dot">{dot}</div>'
                    f'<strong>{stage}</strong><div class="stage-state">{state}</div></div>',
                    unsafe_allow_html=True,
                )


def show_status():
    st.header("Repair Status")
    st.caption("Demo/placeholder values — not live results.")
    metrics = [
        ("Status", "Ready to start"),
        ("Attempts", "0 / 3"),
        ("Files Changed", "0"),
        ("Tests Fixed", "0"),
        ("Regressions", "0"),
        ("Guard Rejections", "0"),
    ]
    for start in range(0, len(metrics), 3):
        columns = st.columns(3)
        for column, (label, value) in zip(columns, metrics[start : start + 3]):
            with column:
                st.metric(label, value)


def show_repair_plan():
    with st.expander("🧠 Repair Plan — example content", expanded=False):
        st.warning("This is demonstration content and was not generated by a backend.")
        st.markdown("**Suspected Root Cause**")
        st.write("The selected function contains incorrect logic.")
        st.markdown("**Files to Change**")
        st.code("calculator.py", language="text")
        st.markdown("**Functions**")
        st.code("add()", language="python")
        st.markdown("**Reasoning**")
        st.write("The addition function is using subtraction instead of addition.")


def show_code_changes():
    st.header("🔧 Proposed Code Changes")
    st.caption("Example only — no patch has been generated or applied.")
    st.code("- return a - b\n+ return a + b", language="diff")
    st.caption("Example patch — actual patch generation will be connected later.")


def show_verification():
    st.header("✅ Verification")
    st.caption("Checks are displayed for the planned UI only; none are executed.")
    st.table(
        [
            {"Check": "Python Syntax / AST", "Status": "Pending"},
            {"Check": "Undefined Names", "Status": "Pending"},
            {"Check": "Import Validation", "Status": "Pending"},
            {"Check": "Test Suite", "Status": "Pending"},
            {"Check": "Regression Check", "Status": "Pending"},
        ]
    )


def show_generated_tests():
    st.header("🧪 Generated Tests")
    st.warning("Demonstration data only — these tests have not been generated or run.")
    st.code("def test_add():\n    assert add(2, 3) == 5", language="python")
    result_columns = st.columns(2)
    with result_columns[0]:
        st.markdown("**Original Code:** ❌ Failed *(example)*")
    with result_columns[1]:
        st.markdown("**Patched Code:** ✅ Passed *(example)*")


def show_final_result():
    st.header("🎯 Final Result")
    st.markdown(
        '<div class="final-result"><div class="final-label">WAITING FOR REPAIR</div>'
        '<h2>Waiting for repair</h2>'
        '<p>The system will only accept a patch after deterministic verification.</p>'
        '</div>',
        unsafe_allow_html=True,
    )


def show_report():
    st.header("📄 Repair Report")
    with st.expander("Preview example Markdown report", expanded=False):
        st.markdown(DEMO_REPORT)
    st.download_button(
        "⬇️ Download Report",
        data=DEMO_REPORT,
        file_name="ai-code-repair-demo-report.md",
        mime="text/markdown",
    )
    st.caption("The downloadable report is static demonstration content.")


def show_footer():
    st.divider()
    left, right = st.columns([3, 1])
    with left:
        st.markdown("**AI Code Repair Agent**")
        st.caption("Probabilistic Intelligence + Deterministic Verification")
    with right:
        st.caption("HackNext 2026")


def main():
    st.set_page_config(
        page_title="AI Code Repair Agent",
        page_icon="🛠️",
        layout="wide",
        initial_sidebar_state="expanded",
    )
    st.markdown(
        """
        <style>
        .stApp { background: #f5f7fb; }
        [data-testid="stSidebar"] { background: #101827; }
        [data-testid="stSidebar"] * { color: #eef3fb; }
        [data-testid="stSidebar"] input, [data-testid="stSidebar"] [role="combobox"] {
            color: #142033;
        }
        .repo-path {
            padding: 0.85rem 1rem; border: 1px solid #dce3ee; border-radius: 10px;
            background: #fff; color: #38506c; font-family: monospace; overflow-wrap: anywhere;
        }
        .stage-card {
            min-height: 112px; margin: 0.25rem 0 0.65rem; padding: 1rem;
            border: 1px solid #e0e6ef; border-radius: 12px; background: #fff;
            box-shadow: 0 2px 8px rgba(27, 44, 71, 0.04);
        }
        .stage-dot { margin-bottom: 0.45rem; font-size: 1.15rem; }
        .stage-state { margin-top: 0.35rem; color: #748198; font-size: 0.85rem; }
        .final-result {
            padding: 1.5rem; border: 1px solid #cbd8ef; border-left: 5px solid #5478c7;
            border-radius: 12px; background: #fff; box-shadow: 0 4px 14px rgba(27, 44, 71, 0.06);
        }
        .final-result h2 { margin: 0.4rem 0; color: #1c2d49; }
        .final-result p { margin-bottom: 0; color: #61708a; }
        .final-label { color: #5478c7; font-size: 0.74rem; font-weight: 700; letter-spacing: 0.11em; }
        div.stButton > button[kind="primary"] {
            min-height: 3.2rem; border-radius: 10px; font-weight: 700;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )

    repository_path, model, max_attempts, test_timeout = show_sidebar()
    show_header()
    show_request_form(repository_path, model, max_attempts, test_timeout)
    st.divider()
    show_pipeline()
    st.divider()
    show_status()
    show_repair_plan()
    st.divider()
    show_code_changes()
    show_verification()
    show_generated_tests()
    st.divider()
    show_final_result()
    show_report()
    show_footer()


if __name__ == "__main__":
    main()
